"""
Ukrainian geographical districts, aliases, triggers, and oblast mappings.
"""

APOSTROPHES = ("'", "’")


def apostrophe_variants(name: str) -> list[str]:
    if not any(mark in name for mark in APOSTROPHES):
        return [name]
    straight = name.replace("’", "'")
    return [straight, straight.replace("'", "’")]


DISTRICT_CONFIG = {
    "kyiv": {
        "name": "м. Київ",
        "aliases": ["Київ"],
        "oblast": "kyiv",
        "display_name": "Kyiv",
    },
    "bilatserkva": {
        "name": "Білоцерківський район",
        "oblast": "kyiv_oblast",
        "display_name": "Bila Tserkva",
    },
    "boryspil": {
        "name": "Бориспільський район",
        "oblast": "kyiv_oblast",
        "display_name": "Boryspil",
    },
    "brovary": {
        "name": "Броварський район",
        "oblast": "kyiv_oblast",
        "display_name": "Brovary",
    },
    "bucha": {"name": "Бучанський район", "oblast": "kyiv_oblast", "display_name": "Bucha"},
    "vyshhorod": {
        "name": "Вишгородський район",
        "oblast": "kyiv_oblast",
        "display_name": "Vyshhorod",
    },
    "obukhiv": {
        "name": "Обухівський район",
        "oblast": "kyiv_oblast",
        "display_name": "Obukhiv",
    },
    "fastiv": {"name": "Фастівський район", "oblast": "kyiv_oblast", "display_name": "Fastiv"},
    "vinnytsia": {
        "name": "Вінницький район",
        "oblast": "vinnytsia_oblast",
        "display_name": "Vinnytsia",
    },
    "haisyn": {
        "name": "Гайсинський район",
        "oblast": "vinnytsia_oblast",
        "display_name": "Haisyn",
    },
    "zhmerynka": {
        "name": "Жмеринський район",
        "oblast": "vinnytsia_oblast",
        "display_name": "Zhmerynka",
    },
    "mohylivpodilskyi": {
        "name": "Могилів-Подільський район",
        "oblast": "vinnytsia_oblast",
        "display_name": "Mohyliv-Podilskyi",
    },
    "tulchyn": {
        "name": "Тульчинський район",
        "oblast": "vinnytsia_oblast",
        "display_name": "Tulchyn",
    },
    "khmilnyk": {
        "name": "Хмільницький район",
        "oblast": "vinnytsia_oblast",
        "display_name": "Khmilnyk",
        "aliases": [
            "м. Хмільник",
            "Хмільник",
            "Хмільнику",
            "місто Хмільник",
            "Хмільницька територіальна громада",
            "Хмільницька міська територіальна громада",
            "Хмільницька громада",
            "Хмільницька ТГ",
        ],
    },
    "lutsk": {"name": "Луцький район", "oblast": "volyn_oblast", "display_name": "Lutsk"},
    "volodymyr": {
        "name": "Володимирський район",
        "oblast": "volyn_oblast",
        "aliases": ["Володимир-Волинський район"],
        "display_name": "Volodymyr",
    },
    "kaminkashyrskyi": {
        "name": "Камінь-Каширський район",
        "oblast": "volyn_oblast",
        "display_name": "Kamin-Kashyrskyi",
    },
    "kovel": {"name": "Ковельський район", "oblast": "volyn_oblast", "display_name": "Kovel"},
    "dnipro": {
        "name": "Дніпровський район",
        "oblast": "dnipropetrovsk_oblast",
        "display_name": "Dnipro",
    },
    "kamianske": {
        "name": "Кам'янський район",
        "oblast": "dnipropetrovsk_oblast",
        "display_name": "Kamianske",
    },
    "kryvyirih": {
        "name": "Криворізький район",
        "oblast": "dnipropetrovsk_oblast",
        "display_name": "Kryvyi Rih",
    },
    "nikopol": {
        "name": "м. Нікополь",
        "aliases": ["Нікополь"],
        "oblast": "dnipropetrovsk_oblast",
        "display_name": "Nikopol",
        "triggers": [
            "м. Нікополь",
            "Нікополь",
            "Нікополі",
            "місто Нікополь",
            "місті Нікополь",
            "місті Нікополі",
            "м.Нікополь",
            "м Нікополь",
            "Нікопольська територіальна громада",
            "Нікопольська міська територіальна громада",
            "Нікопольська громада",
            "Нікопольська ТГ",
        ],
        "alert_triggers": {
            "threat_of_shelling": [
                "артилерійський обстріл",
                "Загроза артобстрілу",
                "Загроза обстрілу",
            ],
            "threat_of_shelling_cancelled": ["Відбій загрози артобстрілу"],
            "air_raid_alert": ["Повітряна тривога"],
            "air_raid_alert_cancelled": ["Відбій тривоги"],
        },
    },
    "nikopol_district": {
        "name": "Нікопольський район",
        "oblast": "dnipropetrovsk_oblast",
        "display_name": "Nikopol Raion",
        "triggers": [
            "Нікопольський район",
            "Нікопольському районі",
            "Нікопольського району",
        ],
    },
    "pavlohrad": {
        "name": "Павлоградський район",
        "oblast": "dnipropetrovsk_oblast",
        "display_name": "Pavlohrad",
    },
    "samar": {
        "name": "Самарівський район",
        "oblast": "dnipropetrovsk_oblast",
        "aliases": ["Новомосковський район"],
        "display_name": "Samar",
    },
    "synelnykove": {
        "name": "Синельниківський район",
        "oblast": "dnipropetrovsk_oblast",
        "display_name": "Synelnykove",
    },
    "zhytomyr": {
        "name": "Житомирський район",
        "oblast": "zhytomyr_oblast",
        "display_name": "Zhytomyr",
    },
    "berdychiv": {
        "name": "Бердичівський район",
        "oblast": "zhytomyr_oblast",
        "display_name": "Berdychiv",
    },
    "zviahel": {
        "name": "Звягельський район",
        "oblast": "zhytomyr_oblast",
        "aliases": ["Новоград-Волинський район"],
        "display_name": "Zviahel",
    },
    "korosten": {
        "name": "Коростенський район",
        "oblast": "zhytomyr_oblast",
        "display_name": "Korosten",
    },
    "uzhhorod": {
        "name": "Ужгородський район",
        "oblast": "zakarpattia_oblast",
        "display_name": "Uzhhorod",
    },
    "berehove": {
        "name": "Берегівський район",
        "oblast": "zakarpattia_oblast",
        "display_name": "Berehove",
    },
    "mukachevo": {
        "name": "Мукачівський район",
        "oblast": "zakarpattia_oblast",
        "display_name": "Mukachevo",
    },
    "rakhiv": {
        "name": "Рахівський район",
        "oblast": "zakarpattia_oblast",
        "display_name": "Rakhiv",
    },
    "tiachiv": {
        "name": "Тячівський район",
        "oblast": "zakarpattia_oblast",
        "display_name": "Tiachiv",
    },
    "khust": {
        "name": "Хустський район",
        "oblast": "zakarpattia_oblast",
        "display_name": "Khust",
    },
    "zaporizhzhia": {
        "name": "м. Запоріжжя",
        "oblast": "zaporizhzhia_oblast",
        "aliases": ["Запоріжжя"],
        "display_name": "Zaporizhzhia",
        "triggers": [
            "м. Запоріжжя",
            "Запоріжжя",
            "Запоріжжі",
            "місто Запоріжжя",
            "місті Запоріжжя",
            "місті Запоріжжі",
            "м.Запоріжжя",
            "м Запоріжжя",
            "Запорізька територіальна громада",
            "Запорізька міська територіальна громада",
            "Запорізька громада",
            "Запорізька ТГ",
        ],
    },
    "zaporizhzhia_district": {
        "name": "Запорізький район",
        "oblast": "zaporizhzhia_oblast",
        "display_name": "Zaporizhzhia Raion",
        "triggers": [
            "Запорізький район",
            "Запорізькому районі",
            "Запорізького району",
        ],
    },
    "berdiansk": {
        "name": "Бердянський район",
        "oblast": "zaporizhzhia_oblast",
        "display_name": "Berdiansk",
    },
    "vasylivka": {
        "name": "Василівський район",
        "oblast": "zaporizhzhia_oblast",
        "display_name": "Vasylivka",
    },
    "melitopol": {
        "name": "Мелітопольський район",
        "oblast": "zaporizhzhia_oblast",
        "display_name": "Melitopol",
    },
    "polohy": {
        "name": "Пологівський район",
        "oblast": "zaporizhzhia_oblast",
        "display_name": "Polohy",
    },
    "ivanofrankivsk": {
        "name": "Івано-Франківський район",
        "oblast": "ivanofrankivsk_oblast",
        "display_name": "Ivano-Frankivsk",
    },
    "verkhovyna": {
        "name": "Верховинський район",
        "oblast": "ivanofrankivsk_oblast",
        "display_name": "Verkhovyna",
    },
    "kalush": {
        "name": "Калуський район",
        "oblast": "ivanofrankivsk_oblast",
        "display_name": "Kalush",
    },
    "kolomyia": {
        "name": "Коломийський район",
        "oblast": "ivanofrankivsk_oblast",
        "display_name": "Kolomyia",
    },
    "kosiv": {
        "name": "Косівський район",
        "oblast": "ivanofrankivsk_oblast",
        "display_name": "Kosiv",
    },
    "nadvirna": {
        "name": "Надвірнянський район",
        "oblast": "ivanofrankivsk_oblast",
        "display_name": "Nadvirna",
    },
    "kropyvnytskyi": {
        "name": "Кропивницький район",
        "oblast": "kirovohrad_oblast",
        "display_name": "Kropyvnytskyi",
    },
    "holovanivsk": {
        "name": "Голованівський район",
        "oblast": "kirovohrad_oblast",
        "display_name": "Holovanivsk",
    },
    "novoukrainka": {
        "name": "Новоукраїнський район",
        "oblast": "kirovohrad_oblast",
        "display_name": "Novoukrainka",
    },
    "oleksandriia": {
        "name": "Олександрійський район",
        "oblast": "kirovohrad_oblast",
        "display_name": "Oleksandriia",
    },
    "lviv": {"name": "Львівський район", "oblast": "lviv_oblast", "display_name": "Lviv"},
    "drohobych": {
        "name": "Дрогобицький район",
        "oblast": "lviv_oblast",
        "display_name": "Drohobych",
    },
    "zolochiv": {
        "name": "Золочівський район",
        "oblast": "lviv_oblast",
        "display_name": "Zolochiv",
    },
    "sambir": {
        "name": "Самбірський район",
        "oblast": "lviv_oblast",
        "display_name": "Sambir",
    },
    "stryi": {"name": "Стрийський район", "oblast": "lviv_oblast", "display_name": "Stryi"},
    "sheptytskyi": {
        "name": "Шептицький район",
        "oblast": "lviv_oblast",
        "aliases": [
            "Червоноградський район",
            "м. Червоноград",
            "Червоноград",
            "Шептицький",
            "м. Шептицький",
        ],
        "display_name": "Sheptytskyi",
    },
    "yavoriv": {
        "name": "Яворівський район",
        "oblast": "lviv_oblast",
        "display_name": "Yavoriv",
    },
    "mykolaiv": {
        "name": "Миколаївський район",
        "oblast": "mykolaiv_oblast",
        "display_name": "Mykolaiv",
    },
    "bashtanka": {
        "name": "Баштанський район",
        "oblast": "mykolaiv_oblast",
        "display_name": "Bashtanka",
    },
    "voznesensk": {
        "name": "Вознесенський район",
        "oblast": "mykolaiv_oblast",
        "display_name": "Voznesensk",
    },
    "pervomaisk": {
        "name": "Первомайський район",
        "oblast": "mykolaiv_oblast",
        "display_name": "Pervomaisk",
    },
    "odesa": {"name": "Одеський район", "oblast": "odesa_oblast", "display_name": "Odesa"},
    "berezivka": {
        "name": "Березівський район",
        "oblast": "odesa_oblast",
        "display_name": "Berezivka",
    },
    "bilhoroddnistrovskyi": {
        "name": "Білгород-Дністровський район",
        "oblast": "odesa_oblast",
        "display_name": "Bilhorod-Dnistrovskyi",
    },
    "bolhrad": {
        "name": "Болградський район",
        "oblast": "odesa_oblast",
        "display_name": "Bolhrad",
    },
    "izmail": {"name": "Ізмаїльський район", "oblast": "odesa_oblast", "display_name": "Izmail"},
    "podilsk": {
        "name": "Подільський район",
        "oblast": "odesa_oblast",
        "display_name": "Podilsk",
    },
    "rozdilna": {
        "name": "Роздільнянський район",
        "oblast": "odesa_oblast",
        "display_name": "Rozdilna",
    },
    "poltava": {"name": "Полтавський район", "oblast": "poltava_oblast", "display_name": "Poltava"},
    "kremenchuk": {
        "name": "Кременчуцький район",
        "oblast": "poltava_oblast",
        "display_name": "Kremenchuk",
    },
    "lubny": {
        "name": "Лубенський район",
        "oblast": "poltava_oblast",
        "display_name": "Lubny",
    },
    "myrhorod": {
        "name": "Миргородський район",
        "oblast": "poltava_oblast",
        "display_name": "Myrhorod",
    },
    "rivne": {"name": "Рівненський район", "oblast": "rivne_oblast", "display_name": "Rivne"},
    "varash": {
        "name": "Вараський район",
        "oblast": "rivne_oblast",
        "display_name": "Varash",
    },
    "dubno": {
        "name": "Дубенський район",
        "oblast": "rivne_oblast",
        "display_name": "Dubno",
    },
    "sarny": {
        "name": "Сарненський район",
        "oblast": "rivne_oblast",
        "display_name": "Sarny",
    },
    "sumy": {"name": "Сумський район", "oblast": "sumy_oblast", "display_name": "Sumy"},
    "konotop": {
        "name": "Конотопський район",
        "oblast": "sumy_oblast",
        "display_name": "Konotop",
    },
    "okhtyrka": {
        "name": "Охтирський район",
        "oblast": "sumy_oblast",
        "display_name": "Okhtyrka",
    },
    "romny": {
        "name": "Роменський район",
        "oblast": "sumy_oblast",
        "display_name": "Romny",
    },
    "shostka": {
        "name": "Шосткинський район",
        "oblast": "sumy_oblast",
        "display_name": "Shostka",
    },
    "ternopil": {
        "name": "Тернопільський район",
        "oblast": "ternopil_oblast",
        "display_name": "Ternopil",
    },
    "kremenets": {
        "name": "Кременецький район",
        "oblast": "ternopil_oblast",
        "display_name": "Kremenets",
    },
    "chortkiv": {
        "name": "Чортківський район",
        "oblast": "ternopil_oblast",
        "display_name": "Chortkiv",
    },
    "kharkiv": {
        "name": "м. Харків",
        "oblast": "kharkiv_oblast",
        "aliases": ["Харків"],
        "display_name": "Kharkiv",
        "triggers": [
            "м. Харків",
            "Харків",
            "Харкові",
            "Харкова",
            "місто Харків",
            "місті Харків",
            "місті Харкові",
            "м.Харків",
            "м Харків",
            "Харківська територіальна громада",
            "Харківська міська територіальна громада",
            "Харківська громада",
            "Харківська ТГ",
        ],
    },
    "kharkiv_district": {
        "name": "Харківський район",
        "oblast": "kharkiv_oblast",
        "display_name": "Kharkiv Raion",
        "triggers": [
            "Харківський район",
            "Харківському районі",
            "Харківського району",
        ],
    },
    "berestyn": {
        "name": "Берестинський район",
        "oblast": "kharkiv_oblast",
        "aliases": ["Красноградський район"],
        "display_name": "Berestyn",
    },
    "bohodukhiv": {
        "name": "Богодухівський район",
        "oblast": "kharkiv_oblast",
        "display_name": "Bohodukhiv",
    },
    "izium": {
        "name": "Ізюмський район",
        "oblast": "kharkiv_oblast",
        "display_name": "Izium",
    },
    "kupiansk": {
        "name": "Куп'янський район",
        "oblast": "kharkiv_oblast",
        "display_name": "Kupiansk",
    },
    "lozova": {
        "name": "Лозівський район",
        "oblast": "kharkiv_oblast",
        "display_name": "Lozova",
    },
    "chuhuiv": {
        "name": "Чугуївський район",
        "oblast": "kharkiv_oblast",
        "display_name": "Chuhuiv",
    },
    "kherson": {"name": "Херсонський район", "oblast": "kherson_oblast", "display_name": "Kherson"},
    "beryslav": {
        "name": "Бериславський район",
        "oblast": "kherson_oblast",
        "display_name": "Beryslav",
    },
    "henichesk": {
        "name": "Генічеський район",
        "oblast": "kherson_oblast",
        "display_name": "Henichesk",
    },
    "kakhovka": {
        "name": "Каховський район",
        "oblast": "kherson_oblast",
        "display_name": "Kakhovka",
    },
    "skadovsk": {
        "name": "Скадовський район",
        "oblast": "kherson_oblast",
        "display_name": "Skadovsk",
    },
    "khmelnytskyi": {
        "name": "Хмельницький район",
        "oblast": "khmelnytskyi_oblast",
        "display_name": "Khmelnytskyi",
    },
    "kamianetspodilskyi": {
        "name": "Кам'янець-Подільський район",
        "oblast": "khmelnytskyi_oblast",
        "display_name": "Kamianets-Podilskyi",
    },
    "shepetivka": {
        "name": "Шепетівський район",
        "oblast": "khmelnytskyi_oblast",
        "display_name": "Shepetivka",
    },
    "cherkasy": {
        "name": "Черкаський район",
        "oblast": "cherkasy_oblast",
        "display_name": "Cherkasy",
    },
    "zvenyhorodka": {
        "name": "Звенигородський район",
        "oblast": "cherkasy_oblast",
        "display_name": "Zvenyhorodka",
    },
    "zolotonosha": {
        "name": "Золотоніський район",
        "oblast": "cherkasy_oblast",
        "display_name": "Zolotonosha",
    },
    "uman": {"name": "Уманський район", "oblast": "cherkasy_oblast", "display_name": "Uman"},
    "chernivtsi": {
        "name": "Чернівецький район",
        "oblast": "chernivtsi_oblast",
        "display_name": "Chernivtsi",
    },
    "vyzhnytsia": {
        "name": "Вижницький район",
        "oblast": "chernivtsi_oblast",
        "display_name": "Vyzhnytsia",
    },
    "dnistrovskyi": {
        "name": "Дністровський район",
        "oblast": "chernivtsi_oblast",
        "display_name": "Dnistrovskyi",
    },
    "chernihiv": {
        "name": "Чернігівський район",
        "oblast": "chernihiv_oblast",
        "display_name": "Chernihiv",
    },
    "koriukivka": {
        "name": "Корюківський район",
        "oblast": "chernihiv_oblast",
        "display_name": "Koriukivka",
    },
    "nizhyn": {
        "name": "Ніжинський район",
        "oblast": "chernihiv_oblast",
        "display_name": "Nizhyn",
    },
    "novhorodsiverskyi": {
        "name": "Новгород-Сіверський район",
        "oblast": "chernihiv_oblast",
        "display_name": "Novhorod-Siverskyi",
    },
    "pryluky": {
        "name": "Прилуцький район",
        "oblast": "chernihiv_oblast",
        "display_name": "Pryluky",
    },
    "volnovakha": {
        "name": "Волноваський район",
        "oblast": "donetsk_oblast",
        "display_name": "Volnovakha",
    },
    "bakhmut": {
        "name": "Бахмутський район",
        "oblast": "donetsk_oblast",
        "display_name": "Bakhmut",
    },
    "donetsk": {
        "name": "Донецький район",
        "oblast": "donetsk_oblast",
        "display_name": "Donetsk",
    },
    "horlivka": {
        "name": "Горлівський район",
        "oblast": "donetsk_oblast",
        "display_name": "Horlivka",
    },
    "pokrovsk": {
        "name": "Покровський район",
        "oblast": "donetsk_oblast",
        "display_name": "Pokrovsk",
    },
    "kramatorsk": {
        "name": "Краматорський район",
        "oblast": "donetsk_oblast",
        "display_name": "Kramatorsk",
    },
    "mariupol": {
        "name": "Маріупольський район",
        "oblast": "donetsk_oblast",
        "display_name": "Mariupol",
    },
    "kalmiuske": {
        "name": "Кальміуський район",
        "oblast": "donetsk_oblast",
        "display_name": "Kalmiuske",
    },
    "alchevsk": {
        "name": "Алчевський район",
        "oblast": "luhansk_oblast",
        "display_name": "Alchevsk",
    },
    "dovzhansk": {
        "name": "Довжанський район",
        "oblast": "luhansk_oblast",
        "display_name": "Dovzhansk",
    },
    "luhansk": {
        "name": "Луганський район",
        "oblast": "luhansk_oblast",
        "display_name": "Luhansk",
    },
    "rovenky": {
        "name": "Ровеньківський район",
        "oblast": "luhansk_oblast",
        "display_name": "Rovenky",
    },
    "svatove": {
        "name": "Сватівський район",
        "oblast": "luhansk_oblast",
        "display_name": "Svatove",
    },
    "siverskodonetsk": {
        "name": "Сіверськодонецький район",
        "aliases": ["Сєвєродонецький район"],
        "oblast": "luhansk_oblast",
        "display_name": "Siverskodonetsk",
    },
    "starobilsk": {
        "name": "Старобільський район",
        "oblast": "luhansk_oblast",
        "display_name": "Starobilsk",
    },
    "shchastia": {
        "name": "Щастинський район",
        "oblast": "luhansk_oblast",
        "display_name": "Shchastia",
    },
    "crimea": {
        "name": "Крим",
        "aliases": ["Автономна Республіка Крим", "АР Крим"],
        "oblast": "crimea",
        "display_name": "Crimea",
    },
}

for _key, _conf in DISTRICT_CONFIG.items():
    if "triggers" in _conf:
        _forms = _conf["triggers"]
    else:
        _forms = [_conf["name"], *_conf.get("aliases", ())]
    _conf["triggers"] = [form for raw in _forms for form in apostrophe_variants(raw)]
    if "city_triggers" in _conf:
        _conf["city_triggers"] = [
            form for raw in _conf["city_triggers"] for form in apostrophe_variants(raw)
        ]

OBLAST_TRIGGERS = {
    "cherkasy_oblast": ["Черкаська область"],
    "chernihiv_oblast": ["Чернігівська область"],
    "chernivtsi_oblast": ["Чернівецька область"],
    "dnipropetrovsk_oblast": ["Дніпропетровська область"],
    "donetsk_oblast": ["Донецька область"],
    "ivanofrankivsk_oblast": ["Івано-Франківська область"],
    "kharkiv_oblast": ["Харківська область"],
    "kherson_oblast": ["Херсонська область"],
    "khmelnytskyi_oblast": ["Хмельницька область"],
    "kirovohrad_oblast": ["Кіровоградська область"],
    "kyiv_oblast": ["Київська область"],
    "luhansk_oblast": ["Луганська область"],
    "lviv_oblast": ["Львівська область"],
    "mykolaiv_oblast": ["Миколаївська область"],
    "odesa_oblast": ["Одеська область"],
    "poltava_oblast": ["Полтавська область"],
    "rivne_oblast": ["Рівненська область"],
    "sumy_oblast": ["Сумська область"],
    "ternopil_oblast": ["Тернопільська область"],
    "vinnytsia_oblast": ["Вінницька область"],
    "volyn_oblast": ["Волинська область"],
    "zakarpattia_oblast": ["Закарпатська область"],
    "zaporizhzhia_oblast": ["Запорізька область"],
    "zhytomyr_oblast": ["Житомирська область"],
}

OBLAST_NAMES = {
    "cherkasy_oblast": "Черкаська область",
    "chernihiv_oblast": "Чернігівська область",
    "chernivtsi_oblast": "Чернівецька область",
    "crimea": "Крим",
    "dnipropetrovsk_oblast": "Дніпропетровська область",
    "donetsk_oblast": "Донецька область",
    "ivanofrankivsk_oblast": "Івано-Франківська область",
    "kharkiv_oblast": "Харківська область",
    "kherson_oblast": "Херсонська область",
    "khmelnytskyi_oblast": "Хмельницька область",
    "kirovohrad_oblast": "Кіровоградська область",
    "kyiv": "м. Київ",
    "kyiv_oblast": "Київська область",
    "luhansk_oblast": "Луганська область",
    "lviv_oblast": "Львівська область",
    "mykolaiv_oblast": "Миколаївська область",
    "odesa_oblast": "Одеська область",
    "poltava_oblast": "Полтавська область",
    "rivne_oblast": "Рівненська область",
    "sevastopol": "Севастополь",
    "sumy_oblast": "Сумська область",
    "ternopil_oblast": "Тернопільська область",
    "vinnytsia_oblast": "Вінницька область",
    "volyn_oblast": "Волинська область",
    "zakarpattia_oblast": "Закарпатська область",
    "zaporizhzhia_oblast": "Запорізька область",
    "zhytomyr_oblast": "Житомирська область",
}

LOCATION_LOCATIVE = {
    "bilatserkva": "у Білій Церкві",
    "bucha": "у Бучі",
    "cherkasy": "у Черкасах",
    "chernihiv": "у Чернігові",
    "chernivtsi": "у Чернівцях",
    "dnipro": "у Дніпрі",
    "fastiv": "у Фастові",
    "ivanofrankivsk": "в Івано-Франківську",
    "izmail": "в Ізмаїлі",
    "kamianske": "у Кам'янському",
    "kharkiv": "у Харкові",
    "kherson": "у Херсоні",
    "khmelnytskyi": "у Хмельницькому",
    "kovel": "у Ковелі",
    "kremenchuk": "у Кременчуці",
    "kropyvnytskyi": "у Кропивницькому",
    "kryvyirih": "у Кривому Розі",
    "kyiv": "у Києві",
    "lutsk": "у Луцьку",
    "lviv": "у Львові",
    "mykolaiv": "у Миколаєві",
    "nikopol": "у Нікополі",
    "odesa": "в Одесі",
    "pervomaisk": "у Первомайську",
    "poltava": "у Полтаві",
    "rivne": "у Рівному",
    "sumy": "у Сумах",
    "ternopil": "у Тернополі",
    "uman": "в Умані",
    "uzhhorod": "в Ужгороді",
    "vinnytsia": "у Вінниці",
    "zaporizhzhia": "у Запоріжжі",
    "zhytomyr": "у Житомирі",
    "zolotonosha": "у Золотоноші",
    "zvenyhorodka": "у Звенигородці",
    "boryspil": "у Борисполі",
    "brovary": "у Броварах",
    "vyshhorod": "у Вишгороді",
    "obukhiv": "в Обухові",
    "volnovakha": "у Волноваському районі",
    "bakhmut": "у Бахмутському районі",
    "donetsk": "у Донецькому районі",
    "horlivka": "у Горлівському районі",
    "pokrovsk": "у Покровському районі",
    "kramatorsk": "у Краматорському районі",
    "mariupol": "у Маріупольському районі",
    "kalmiuske": "у Кальміуському районі",
    "alchevsk": "в Алчевському районі",
    "dovzhansk": "у Довжанському районі",
    "luhansk": "у Луганському районі",
    "rovenky": "у Ровеньківському районі",
    "svatove": "у Сватівському районі",
    "siverskodonetsk": "у Сіверськодонецькому районі",
    "starobilsk": "у Старобільському районі",
    "shchastia": "у Щастинському районі",
    "crimea": "у Криму",
    "kharkiv_district": "у Харківському районі",
    "nikopol_district": "у Нікопольському районі",
    "zaporizhzhia_district": "у Запорізькому районі",
}

DISTRICTS_BY_OBLAST = {}
for district_key, conf in DISTRICT_CONFIG.items():
    DISTRICTS_BY_OBLAST.setdefault(conf["oblast"], []).append(district_key)
